print('Olá, mundo!')
print('Perfeito dia')
print('Vou fazer a unha hoje')
print ('Qualquer coisa')
print('Brás amanhã')
print('Estou com tanto sono')
print('Timãooooo')
print('Bom dia, boa tarde, boa noite')
print('Dormi com a Iza hoje')
print('Todo dia é dia')